// export const data = {
//   "status": "OK",
//   "request_id": "81a93af3-8836-4f32-a01c-416a574cc4a0",
//   "data": {
//     "total_products": 9985,
//     "country": "US",
//     "domain": "www.amazon.com",
//     "products": [
//       {
//         "asin": "B0BQ118F2T",
//         "product_title": "Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue",
//         "product_price": "$99.99",
//         "product_original_price": "$169.99",
//         "currency": "USD",
//         "product_star_rating": "4",
//         "product_num_ratings": 2740,
//         "product_url": "https://www.amazon.com/dp/B0BQ118F2T",
//         "product_photo": "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 22,
//         "product_minimum_offer_price": "$72.06",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "3K+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
//       },
//       {
//         "asin": "B0CN1QSH8Q",
//         "product_title": "SAMSUNG Galaxy A15 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Expandable Storage, Knox Security, Super Fast Charging, Hi-Res Camera, US Version, 2024, Blue Black",
//         "product_price": "$199.99",
//         "product_original_price": null,
//         "currency": "USD",
//         "product_star_rating": "4.1",
//         "product_num_ratings": 323,
//         "product_url": "https://www.amazon.com/dp/B0CN1QSH8Q",
//         "product_photo": "https://m.media-amazon.com/images/I/61s0ZzwzSCL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 28,
//         "product_minimum_offer_price": "$158.23",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": true,
//         "sales_volume": "2K+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
//       },
//       {
//         "asin": "B0CRVWXJ6H",
//         "product_title": "Samsung Galaxy A25 5G (SM-A256E/DS), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) - (Blue Black)",
//         "product_price": "$185.00",
//         "product_original_price": "$199.00",
//         "currency": "USD",
//         "product_star_rating": "4.1",
//         "product_num_ratings": 107,
//         "product_url": "https://www.amazon.com/dp/B0CRVWXJ6H",
//         "product_photo": "https://m.media-amazon.com/images/I/51m744UUjYL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 20,
//         "product_minimum_offer_price": "$169.99",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "1K+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Sat, Jul 6"
//       },
//       {
//         "asin": "B0CTD42NJZ",
//         "product_title": "Samsung Galaxy A15 5G (SM-156M/DSN), 256GB 8GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
//         "product_price": "$175.00",
//         "product_original_price": "$189.98",
//         "currency": "USD",
//         "product_star_rating": "4.5",
//         "product_num_ratings": 40,
//         "product_url": "https://www.amazon.com/dp/B0CTD42NJZ",
//         "product_photo": "https://m.media-amazon.com/images/I/31bNhi6E3eL._AC_UY650_FMwebp_QL65_.jpg",
//         "product_num_offers": 8,
//         "product_minimum_offer_price": "$174.95",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "500+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Sat, Jul 6 Only 14 left in stock - order soon."
//       },
//       {
//         "asin": "B0CTBCDCDH",
//         "product_title": "Samsung Galaxy A05s (SM-A057M/DS), 128GB 4GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Violet)",
//         "product_price": "$122.50",
//         "product_original_price": "$128.95",
//         "currency": "USD",
//         "product_star_rating": "4",
//         "product_num_ratings": 20,
//         "product_url": "https://www.amazon.com/dp/B0CTBCDCDH",
//         "product_photo": "https://m.media-amazon.com/images/I/21f9A+OzosL._AC_UY365_FMwebp_QL65_.jpg",
//         "product_num_offers": 9,
//         "product_minimum_offer_price": "$122.00",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "200+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Sat, Jul 6"
//       },
//       {
//         "asin": "B0CHH6X6H2",
//         "product_title": "Total by Verizon Samsung Galaxy A03s, 32GB, Black - Prepaid Smartphone (Locked)",
//         "product_price": "$49.88",
//         "product_original_price": null,
//         "currency": "USD",
//         "product_star_rating": "4",
//         "product_num_ratings": 156,
//         "product_url": "https://www.amazon.com/dp/B0CHH6X6H2",
//         "product_photo": "https://m.media-amazon.com/images/I/812woqv69CL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 4,
//         "product_minimum_offer_price": "$45.00",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "500+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
//       },
//       {
//         "asin": "B08PMYLKVF",
//         "product_title": "Apple iPhone 12 Pro, 128GB, Pacific Blue - Fully Unlocked (Renewed)",
//         "product_price": "$374.95",
//         "product_original_price": null,
//         "currency": "USD",
//         "product_star_rating": "4.2",
//         "product_num_ratings": 9350,
//         "product_url": "https://www.amazon.com/dp/B08PMYLKVF",
//         "product_photo": "https://m.media-amazon.com/images/I/51n-83C8HYL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 42,
//         "product_minimum_offer_price": "$297.29",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": false,
//         "climate_pledge_friendly": true,
//         "sales_volume": "2K+ bought in past month",
//         "delivery": "FREE delivery Tomorrow, Jul 3"
//       },
//       {
//         "asin": "B086QB7WZ1",
//         "product_title": "AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black",
//         "product_price": "$49.31",
//         "product_original_price": "$56.95",
//         "currency": "USD",
//         "product_star_rating": "4.3",
//         "product_num_ratings": 26344,
//         "product_url": "https://www.amazon.com/dp/B086QB7WZ1",
//         "product_photo": "https://m.media-amazon.com/images/I/81vjTHTF9WL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 13,
//         "product_minimum_offer_price": "$17.82",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "4K+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Sat, Jul 6"
//       },
//       {
//         "asin": "B0CSF1MRRR",
//         "product_title": "BLU G63 | 2023 | 3-Day Battery | Unlocked | 6.8” HD+ Infinity Display | 128/4GB | Dual 13MP Camera | US Version | US Warranty | Green",
//         "product_price": "$89.99",
//         "product_original_price": "$129.99",
//         "currency": "USD",
//         "product_star_rating": "4.1",
//         "product_num_ratings": 35,
//         "product_url": "https://www.amazon.com/dp/B0CSF1MRRR",
//         "product_photo": "https://m.media-amazon.com/images/I/71EAB02TrzL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 3,
//         "product_minimum_offer_price": "$89.97",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "500+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Sat, Jul 6"
//       },
//       {
//         "asin": "B0CHHL5R3H",
//         "product_title": "Total by Verizon TCL 30 Z, 32GB, Black - Prepaid Smartphone (Locked)",
//         "product_price": "$39.99",
//         "product_original_price": null,
//         "currency": "USD",
//         "product_star_rating": "3.9",
//         "product_num_ratings": 27,
//         "product_url": "https://www.amazon.com/dp/B0CHHL5R3H",
//         "product_photo": "https://m.media-amazon.com/images/I/718+xprSIBL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 1,
//         "product_minimum_offer_price": "$39.99",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "300+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
//       },
//       {
//         "asin": "B096T6Y623",
//         "product_title": "Samsung Galaxy S21 Ultra 5G, US Version, 128GB, Phantom Black - Unlocked (Renewed)",
//         "product_price": "$308.99",
//         "product_original_price": null,
//         "currency": "USD",
//         "product_star_rating": "4",
//         "product_num_ratings": 2050,
//         "product_url": "https://www.amazon.com/dp/B096T6Y623",
//         "product_photo": "https://m.media-amazon.com/images/I/61dlAm9BpqL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 62,
//         "product_minimum_offer_price": "$269.00",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": true,
//         "sales_volume": "2K+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
//       },
//       {
//         "asin": "B08FRS8NPP",
//         "product_title": "Samsung Galaxy S20+ 5G 128GB Fully Unlocked Smartphone (Renewed)",
//         "product_price": "$209.99",
//         "product_original_price": "$299.60",
//         "currency": "USD",
//         "product_star_rating": "4.1",
//         "product_num_ratings": 2757,
//         "product_url": "https://www.amazon.com/dp/B08FRS8NPP",
//         "product_photo": "https://m.media-amazon.com/images/I/61Q9IXJ1zcS._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 74,
//         "product_minimum_offer_price": "$170.00",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": true,
//         "sales_volume": "500+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3 Only 20 left in stock - order soon."
//       },
//       {
//         "asin": "B0BLZN9NDG",
//         "product_title": "SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32GB,6.5&#x27;&#x27; GSM Unlocked,International Version-Black",
//         "product_price": "$89.55",
//         "product_original_price": null,
//         "currency": "USD",
//         "product_star_rating": "3.8",
//         "product_num_ratings": 541,
//         "product_url": "https://www.amazon.com/dp/B0BLZN9NDG",
//         "product_photo": "https://m.media-amazon.com/images/I/71O2YkTlq-L._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 14,
//         "product_minimum_offer_price": "$83.88",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "500+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Sat, Jul 6"
//       },
//       {
//         "asin": "B0CCSZZGT7",
//         "product_title": "TracFone Motorola moto g Play, 32GB, Black - Prepaid Smartphone (Locked)",
//         "product_price": "$47.36",
//         "product_original_price": "$49.99",
//         "currency": "USD",
//         "product_star_rating": "4",
//         "product_num_ratings": 176,
//         "product_url": "https://www.amazon.com/dp/B0CCSZZGT7",
//         "product_photo": "https://m.media-amazon.com/images/I/71pGGUaxezL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 1,
//         "product_minimum_offer_price": "$47.36",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "1K+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
//       },
//       {
//         "asin": "B000050FZP",
//         "product_title": "AT&amp;T 210 Basic Trimline Corded Phone, No AC Power Required, Wall-Mountable, White",
//         "product_price": "$15.95",
//         "product_original_price": null,
//         "currency": "USD",
//         "product_star_rating": "4.2",
//         "product_num_ratings": 19388,
//         "product_url": "https://www.amazon.com/dp/B000050FZP",
//         "product_photo": "https://m.media-amazon.com/images/I/610brW3Dn7L._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 71,
//         "product_minimum_offer_price": "$11.86",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "2K+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 3"
//       },
//       {
//         "asin": "B092NTYZ78",
//         "product_title": "Panasonic Compact Cordless Phone with DECT 6.0, 1.6&quot; Amber LCD and Illuminated HS Keypad, Call Block, Caller ID, Multiple Display Languages - 1 Handset - KX-TGB810S (Black/Silver)",
//         "product_price": "$24.99",
//         "product_original_price": null,
//         "currency": "USD",
//         "product_star_rating": "4.2",
//         "product_num_ratings": 5277,
//         "product_url": "https://www.amazon.com/dp/B092NTYZ78",
//         "product_photo": "https://m.media-amazon.com/images/I/81k6vcykYYL._AC_UY654_FMwebp_QL65_.jpg",
//         "product_num_offers": 14,
//         "product_minimum_offer_price": "$10.49",
//         "is_best_seller": false,
//         "is_amazon_choice": false,
//         "is_prime": true,
//         "climate_pledge_friendly": false,
//         "sales_volume": "1K+ bought in past month",
//         "delivery": "FREE delivery Sun, Jul 7 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 3"
//       }
//     ]
//   }
// }
