const data = {
  "status": "OK",
  "request_id": "81a93af3-8836-4f32-a01c-416a574cc4a0",
  "data": {
    "total_products": 9985,
    "country": "US",
    "domain": "www.amazon.com",
    "products": {
      "phones": [
        {
          "asin": "B0BQ118F2T",
          "quantity": 1,
          "product_title": "Moto G Play 2023",
          "product_price": "$99.99",
          "product_original_price": "$169.99",
          "currency": "USD",
          "product_star_rating": "4",
          "product_num_ratings": 2740,
          "product_url": "https://www.amazon.com/dp/B0BQ118F2T",
          "product_photo": "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 22,
          "product_minimum_offer_price": "$72.06",
          "is_best_seller": false,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
      },
      {
          "asin": "B08J5F3G18",
          "quantity": 1,
          "product_title": "Galaxy S21 5G",
          "product_price": "$699.99",
          "product_original_price": "$799.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 19000,
          "product_url": "https://www.amazon.com/dp/B08J5F3G18",
          "product_photo": "https://m.media-amazon.com/images/I/81kfA-GtWwL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 35,
          "product_minimum_offer_price": "$649.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
      },
      {
          "asin": "B08L5TNJHG",
          "quantity": 1,
          "product_title": "iPhone 12 Pro Max",
          "product_price": "$1049.99",
          "product_original_price": "$1199.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 5000,
          "product_url": "https://www.amazon.com/dp/B08L5TNJHG",
          "product_photo": "https://m.media-amazon.com/images/I/71XXJC7V8tL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$999.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "8K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
      },
      {
          "asin": "B09RWQHBQT",
          "quantity": 1,
          "product_title": "OnePlus 9 Pro",
          "product_price": "$899.99",
          "product_original_price": "$969.99",
          "currency": "USD",
          "product_star_rating": "4.3",
          "product_num_ratings": 2500,
          "product_url": "https://www.amazon.com/dp/B09RWQHBQT",
          "product_photo": "https://m.media-amazon.com/images/I/612ytK4luvL._SL1500_.jpg",
          "product_num_offers": 28,
          "product_minimum_offer_price": "$849.99",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
      },
      {
          "asin": "B08N2MSSZY",
          "quantity": 1,
          "product_title": "Google Pixel 5",
          "product_price": "$699.00",
          "product_original_price": "$799.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 4300,
          "product_url": "https://www.amazon.com/dp/B08N2MSSZY",
          "product_photo": "https://www.chooseyourmobile.com/wp-content/uploads/2020/10/Google-Pixel-5-Sorta-Sage-Colors.jpg",
          "product_num_offers": 21,
          "product_minimum_offer_price": "$679.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
      },
      {
          "asin": "B08P2H5LW2",
          "quantity": 1,
          "product_title": "Sony Xperia 1 II",
          "product_price": "$1198.00",
          "product_original_price": "$1299.99",
          "currency": "USD",
          "product_star_rating": "4.2",
          "product_num_ratings": 2100,
          "product_url": "https://www.amazon.com/dp/B08P2H5LW2",
          "product_photo": "https://cdn.shopify.com/s/files/1/0077/5513/7083/products/2526caa2-d3fe-4699-8f15-5b9998ff6147_2048x.jpg?v=1641829889",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$1150.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
      }
        // Add other phone products here
      ],
      "shoes": [
        {
          "asin": "B07PGL2ZSL",
          "quantity": 1,
          "product_title": "Nike Air Max 270",
          "product_price": "$150.00",
          "product_original_price": "$180.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 1020,
          "product_url": "https://www.amazon.com/dp/B07PGL2ZSL",
          "product_photo": "https://c.static-nike.com/a/images/t_PDP_1280_v1/f_auto/hyn4my0yzq35ol3gpdsa/air-max-270-shoe-nnTrqDGR.jpg",
          "product_num_offers": 5,
          "product_minimum_offer_price": "$140.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08VJKYQKL",
          "quantity": 1,
          "product_title": "Adidas Ultraboost 21",
          "product_price": "$180.00",
          "product_original_price": "$200.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 12000,
          "product_url": "https://www.amazon.com/dp/B08VJKYQKL",
          "product_photo": "https://therunningoutlet.co.uk/wp-content/uploads/2021/07/adidas-mens-ultra-boost-21-S23863-side.jpg",
          "product_num_offers": 28,
          "product_minimum_offer_price": "$160.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07NJ8P1TX",
          "quantity": 1,
          "product_title": "ASICS Gel-Venture 7",
          "product_price": "$70.00",
          "product_original_price": "$80.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 8300,
          "product_url": "https://www.amazon.com/dp/B07NJ8P1TX",
          "product_photo": "https://th.bing.com/th/id/OIP.saqI85HYJ9o5maKpAl0eUAHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 22,
          "product_minimum_offer_price": "$65.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07NNS7X9L",
          "quantity": 1,
          "product_title": "New Balance 574 V2",
          "product_price": "$85.00",
          "product_original_price": "$90.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 4500,
          "product_url": "https://www.amazon.com/dp/B07NNS7X9L",
          "product_photo": "https://th.bing.com/th/id/OIP.WNbtfVIZGLy8REDFDl2h9wHaFP?rs=1&pid=ImgDetMain",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$80.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07QK7N9L9",
          "quantity": 1,
          "product_title": "Puma Tazon 6 FM",
          "product_price": "$65.00",
          "product_original_price": "$75.00",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 6300,
          "product_url": "https://www.amazon.com/dp/B07QK7N9L9",
          "product_photo": "https://th.bing.com/th/id/OIP.YAChyTTifQqVUG9EluAcqQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$60.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08J5VKNLY",
          "quantity": 1,
          "product_title": "Under Armour Charged Assert 8",
          "product_price": "$70.00",
          "product_original_price": "$75.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 9700,
          "product_url": "https://www.amazon.com/dp/B08J5VKNLY",
          "product_photo": "https://m.media-amazon.com/images/I/51fjQKot6RL.jpg",
          "product_num_offers": 25,
          "product_minimum_offer_price": "$65.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "9K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
       
      ],
      "clothes": [
        {
          "asin": "B08D9X3HTF",
          "quantity": 1,
          "product_title": "Levi's 511 Jeans",
          "product_price": "$50.00",
          "product_original_price": "$60.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 13400,
          "product_url": "https://www.amazon.com/dp/B08D9X3HTF",
          "product_photo": "https://th.bing.com/th/id/OIP.3quiXDyoTBWaox7HqXnFwQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 25,
          "product_minimum_offer_price": "$45.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07JHLS6LC",
          "quantity": 1,
          "product_title": "Hanes Fleece Sweatshirt",
          "product_price": "$12.00",
          "product_original_price": "$15.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 19300,
          "product_url": "https://www.amazon.com/dp/B07JHLS6LC",
          "product_photo": "https://th.bing.com/th/id/OIP.d0NBI3L0-pVmVLbriRtWiAHaJ4?rs=1&pid=ImgDetMain",
          "product_num_offers": 22,
          "product_minimum_offer_price": "$10.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "15K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07MZ9MLPB",
          "quantity": 1,
          "product_title": "Amazon Essentials Flannel Shirt",
          "product_price": "$20.00",
          "product_original_price": "$25.00",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 7500,
          "product_url": "https://www.amazon.com/dp/B07MZ9MLPB",
          "product_photo": "https://images-na.ssl-images-amazon.com/images/I/91c568PCvbL.jpg",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$18.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "7K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B084V47FG7",
          "quantity": 1,
          "product_title": "Champion Fleece Hoodie",
          "product_price": "$40.00",
          "product_original_price": "$50.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 10300,
          "product_url": "https://www.amazon.com/dp/B084V47FG7",
          "product_photo": "https://th.bing.com/th/id/OIP.nmeLakXYOGBXFGgxSxTpxgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$35.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "12K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08DHRHTHS",
          "quantity": 1,
          "product_title": "Columbia Fleece Jacket",
          "product_price": "$35.00",
          "product_original_price": "$40.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 9400,
          "product_url": "https://www.amazon.com/dp/B08DHRHTHS",
          "product_photo": "https://th.bing.com/th/id/OIP.t_7186EP1z0PqZEHvLWKDgHaJB?rs=1&pid=ImgDetMain",
          "product_num_offers": 17,
          "product_minimum_offer_price": "$30.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "11K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07YZ4XSG5",
          "quantity": 1,
          "product_title": "Nike Jogger Pants",
          "product_price": "$55.00",
          "product_original_price": "$65.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 4100,
          "product_url": "https://www.amazon.com/dp/B07YZ4XSG5",
          "product_photo": "https://th.bing.com/th/id/OIP.0jpruCATNX5aD80tnlJczQHaJQ?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$50.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
       
        // Add other clothes products here
      ],
      "watches": [
        {
          "asin": "B07W7Y62G7",
          "quantity": 1,
          "product_title": "Fossil Gen 5E Watch",
          "product_price": "$129.99",
          "product_original_price": "$199.00",
          "currency": "USD",
          "product_star_rating": "4.3",
          "product_num_ratings": 1400,
          "product_url": "https://www.amazon.com/dp/B07W7Y62G7",
          "product_photo": "https://th.bing.com/th/id/OIP.4gHEEru5LCHUt8b1sZj8jQHaEv?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$120.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08HZKDV1J",
          "quantity": 1,
          "product_title": "Samsung Galaxy Watch 2",
          "product_price": "$219.99",
          "product_original_price": "$269.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 2800,
          "product_url": "https://www.amazon.com/dp/B08HZKDV1J",
          "product_photo": "https://th.bing.com/th/id/OIP.Z7LjHH890V3HKOfnsPPJJQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$199.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07W6Q1WVG",
          "quantity": 1,
          "product_title": "Garmin Forerunner 245",
          "product_price": "$299.99",
          "product_original_price": "$349.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 1800,
          "product_url": "https://www.amazon.com/dp/B07W6Q1WVG",
          "product_photo": "https://th.bing.com/th/id/OIP.AYEwTNZfVj6LjBQ4nl4ZQQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$289.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08J63FMXL",
          "quantity": 1,
          "product_title": "Fitbit Versa 3",
          "product_price": "$229.95",
          "product_original_price": "$249.95",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 3200,
          "product_url": "https://www.amazon.com/dp/B08J63FMXL",
          "product_photo": "https://th.bing.com/th/id/OIP.BQt503ki9b58GPDEhA-WGgAAAA?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$219.95",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08G9P51G6",
          "quantity": 1,
          "product_title": "Apple Watch Series 6",
          "product_price": "$409.00",
          "product_original_price": "$429.00",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 4600,
          "product_url": "https://www.amazon.com/dp/B08G9P51G6",
          "product_photo": "https://th.bing.com/th/id/OIP.rkV1np8nBTYZkZFsVAr4TQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$399.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07ZDRD5Y7",
          "quantity": 1,
          "product_title": "Amazfit Bip U Pro",
          "product_price": "$69.99",
          "product_original_price": "$79.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 2500,
          "product_url": "https://www.amazon.com/dp/B07ZDRD5Y7",
          "product_photo": "https://th.bing.com/th/id/OIP.9VjUJ5RETkYAPuiYPA9pJQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$65.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        
        // Add other watches products here
      ],
      "furniture": [
        {
          "asin": "B07G4HSMFJ",
          "quantity": 1,
          "product_title": "Zinus Mia Bed Frame",
          "product_price": "$118.99",
          "product_original_price": "$149.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 9500,
          "product_url": "https://www.amazon.com/dp/B07G4HSMFJ",
          "product_photo": "https://m.media-amazon.com/images/I/81I+75tgvYS._AC_SL1500_.jpg",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$109.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08B5WVSGQ",
          "quantity": 1,
          "product_title": "Homelegance Accent Chair",
          "product_price": "$192.80",
          "product_original_price": "$219.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 4200,
          "product_url": "https://www.amazon.com/dp/B08B5WVSGQ",
          "product_photo": "https://th.bing.com/th/id/OIP.DcePieM8DTRlksO-t1CTmAHaJC?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$179.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08F3MMK9N",
          "quantity": 1,
          "product_title": "Ashley Memory Foam Mattress",
          "product_price": "$262.00",
          "product_original_price": "$299.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 7800,
          "product_url": "https://www.amazon.com/dp/B08F3MMK9N",
          "product_photo": "https://th.bing.com/th/id/OIP.rn2MFU-5mCWcSsegZCegYwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$249.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07FJ7SMJ5",
          "quantity": 1,
          "product_title": "Zinus Shalini Bed Frame",
          "product_price": "$199.00",
          "product_original_price": "$249.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 8300,
          "product_url": "https://www.amazon.com/dp/B07FJ7SMJ5",
          "product_photo": "https://th.bing.com/th/id/OIP.vxFn8y0LR-QaR4tNsvJ2EQHaFF?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$189.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07G2QHF8R",
          "quantity": 1,
          "product_title": "Walker Edison Buffet Sideboard",
          "product_price": "$294.99",
          "product_original_price": "$349.00",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 5200,
          "product_url": "https://www.amazon.com/dp/B07G2QHF8R",
          "product_photo": "https://th.bing.com/th/id/OIP.vi7GXuhMHscr7PgOxbMxwgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$279.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B085T2KFXJ",
          "quantity": 1,
          "product_title": "Yaheetech Lift Coffee Table",
          "product_price": "$129.99",
          "product_original_price": "$149.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 5500,
          "product_url": "https://www.amazon.com/dp/B085T2KFXJ",
          "product_photo": "https://i.pinimg.com/originals/ed/fa/c6/edfac6d207ae1193982ea21569e1636d.jpg",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$119.99",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        
        // Add other furniture products here
      ],
      "groceries": [
        {
          "asin": "B0899R3GH6",
          "quantity": 1,
          "product_title": "Quaker Oats Oatmeal",
          "product_price": "$3.99",
          "product_original_price": "$4.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 5400,
          "product_url": "https://www.amazon.com/dp/B0899R3GH6",
          "product_photo": "https://th.bing.com/th/id/OIP.-sd2q-D5kqEChGcfKa3CUwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$3.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "10K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B00NP79AIU",
          "quantity": 1,
          "product_title": "Planters Salted Peanuts",
          "product_price": "$5.98",
          "product_original_price": "$7.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 4800,
          "product_url": "https://www.amazon.com/dp/B00NP79AIU",
          "product_photo": "https://th.bing.com/th/id/OIP.yG3hNMUYXPyYuMyxyQP1QgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$5.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B07CQ2F54T",
          "quantity": 1,
          "product_title": "Cascade Dishwasher Pods",
          "product_price": "$16.97",
          "product_original_price": "$19.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 6800,
          "product_url": "https://www.amazon.com/dp/B07CQ2F54T",
          "product_photo": "https://th.bing.com/th/id/OIP.YUFvhpbMvD31AzrOCq7CsgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$15.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "9K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B0863VH2P7",
          "quantity": 1,
          "product_title": "Nestle Coffee-mate Creamer",
          "product_price": "$9.98",
          "product_original_price": "$11.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 5900,
          "product_url": "https://www.amazon.com/dp/B0863VH2P7",
          "product_photo": "https://i5.walmartimages.com/asr/a25ada02-9340-40c3-b906-2dac16daa7f7_1.b99ec8fe6d18f583d80bc5ac2e020cff.jpeg",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$9.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "7K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B084X5P7NC",
          "quantity": 1,
          "product_title": "Happy Belly Wildflower Honey",
          "product_price": "$9.99",
          "product_original_price": "$12.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 4500,
          "product_url": "https://www.amazon.com/dp/B084X5P7NC",
          "product_photo": "https://th.bing.com/th/id/OIP.NBgfX3cN3WmTqnXrDIWgbQAAAA?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$9.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B08R5Z7D3N",
          "quantity": 1,
          "product_title": "StarKist Chunk Light Tuna",
          "product_price": "$7.32",
          "product_original_price": "$9.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 5100,
          "product_url": "https://www.amazon.com/dp/B08R5Z7D3N",
          "product_photo": "https://th.bing.com/th/id/OIP.rKlDzSVjMSjt3_rXruH2hQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$6.50",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B089YJ4SR3",
          "quantity": 1,
          "product_title": "Lavazza Super Crema Coffee",
          "product_price": "$21.39",
          "product_original_price": "$25.00",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 3800,
          "product_url": "https://www.amazon.com/dp/B089YJ4SR3",
          "product_photo": "https://th.bing.com/th/id/OIP.YQA761ksjvmaTnV1MoaWQQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$20.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B01H1R0K0M",
          "quantity": 1,
          "product_title": "Heinz Tomato Ketchup",
          "product_price": "$2.98",
          "product_original_price": "$3.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 7200,
          "product_url": "https://www.amazon.com/dp/B01H1R0K0M",
          "product_photo": "https://th.bing.com/th/id/OIP.n02-w4cRVI3ynL1fyT7XzgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$2.50",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "8K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        {
          "asin": "B00I8GQJPQ",
          "quantity": 1,
          "product_title": "Nature's Path Granola",
          "product_price": "$3.49",
          "product_original_price": "$4.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 2800,
          "product_url": "https://www.amazon.com/dp/B00I8GQJPQ",
          "product_photo": "https://i5.walmartimages.com/asr/e2cd2051-0937-48a0-973c-86244a5b41f5.84240d9ee37c02e3cafaf7ce1602a8d0.png",
          "product_num_offers": 6,
          "product_minimum_offer_price": "$3.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": true,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Tomorrow, Jul 3 on $25 of items shipped by Amazon"
        },
        // Add other groceries products here
      ],
      "laptops": [

        {
          "asin": "B08X4VTR74",
          "quantity": 1,
          "product_title": "Acer Aspire 5",
          "product_price": "$399.99",
          "product_original_price": "$499.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 2100,
          "product_url": "https://www.amazon.com/dp/B08X4VTR74",
          "product_photo": "https://m.media-amazon.com/images/I/71AmKW4yuMS._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$379.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B0877724DZ",
          "quantity": 1,
          "product_title": "MacBook Air",
          "product_price": "$949.99",
          "product_original_price": "$999.99",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 3800,
          "product_url": "https://www.amazon.com/dp/B0877724DZ",
          "product_photo": "https://m.media-amazon.com/images/I/71TPda7cwUL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$939.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08Q3Q3FS7",
          "quantity": 1,
          "product_title": "ASUS VivoBook 15",
          "product_price": "$399.99",
          "product_original_price": "$449.99",
          "currency": "USD",
          "product_star_rating": "4.3",
          "product_num_ratings": 1800,
          "product_url": "https://www.amazon.com/dp/B08Q3Q3FS7",
          "product_photo": "https://i0.wp.com/www.laptopmedia.com/wp-content/uploads/2020/12/3-26-e1609250862259.jpg?fit=1500%2C1005&ssl=1",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$389.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08N6K7Y5P",
          "quantity": 1,
          "product_title": "Lenovo IdeaPad 3",
          "product_price": "$479.99",
          "product_original_price": "$549.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 3200,
          "product_url": "https://www.amazon.com/dp/B08N6K7Y5P",
          "product_photo": "https://th.bing.com/th/id/OIP.NVYv8CdCWqkd8C01EEslSgHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$459.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08F9TFT14",
          "quantity": 1,
          "product_title": "Dell Inspiron 15 3000",
          "product_price": "$379.99",
          "product_original_price": "$449.99",
          "currency": "USD",
          "product_star_rating": "4.2",
          "product_num_ratings": 1500,
          "product_url": "https://www.amazon.com/dp/B08F9TFT14",
          "product_photo": "https://th.bing.com/th/id/OIP.jxpdGKGm9ixoLAXDP7jY5AHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$369.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "1K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08YKPX7DW",
          "quantity": 1,
          "product_title": "HP Pavilion x360",
          "product_price": "$699.99",
          "product_original_price": "$799.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 2500,
          "product_url": "https://www.amazon.com/dp/B08YKPX7DW",
          "product_photo": "https://th.bing.com/th/id/OIP.RA2TefCUM-_JpJ70vw80JQHaFc?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$679.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B0865W5W6B",
          "quantity": 1,
          "product_title": "HP 15-dy1036nr",
          "product_price": "$499.99",
          "product_original_price": "$599.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 2800,
          "product_url": "https://www.amazon.com/dp/B0865W5W6B",
          "product_photo": "https://m.media-amazon.com/images/I/71vvXGmdKWL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$479.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B0868WF8ZW",
          "quantity": 1,
          "product_title": "Lenovo ThinkPad E15",
          "product_price": "$699.99",
          "product_original_price": "$799.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 1900,
          "product_url": "https://www.amazon.com/dp/B0868WF8ZW",
          "product_photo": "https://www.bhphotovideo.com/images/images2500x2500/lenovo_20t8002aus_tp_e15_g2_ryzen_1595848.jpg",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$679.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08QV8FY6D",
          "quantity": 1,
          "product_title": "HP Pavilion x360",
          "product_price": "$699.99",
          "product_original_price": "$799.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 2500,
          "product_url": "https://www.amazon.com/dp/B08QV8FY6D",
          "product_photo": "https://th.bing.com/th/id/OIP.RA2TefCUM-_JpJ70vw80JQHaFc?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$679.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
       
        // Add other laptops products here
      ],
      "headsets": [
        {
          "asin": "B07RGQC7HG",
          "quantity": 1,
          "product_title": "Sony WH-1000XM4",
          "product_price": "$348.00",
          "product_original_price": "$399.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 12000,
          "product_url": "https://www.amazon.com/dp/B07RGQC7HG",
          "product_photo": "https://www.bhphotovideo.com/images/images2500x2500/sony_wh1000xm4_b_wh_1000xm4_wireless_noise_canceling_over_ear_1582549.jpg",
          "product_num_offers": 25,
          "product_minimum_offer_price": "$329.00",
          "is_best_seller": true,
          "is_amazon_choice": false,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "8K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08F3YQ6PT",
          "quantity": 1,
          "product_title": "Bose 700",
          "product_price": "$379.00",
          "product_original_price": "$399.00",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 9500,
          "product_url": "https://www.amazon.com/dp/B08F3YQ6PT",
          "product_photo": "https://th.bing.com/th/id/OIP.IiUjJa7p1QSkMpmBzEuDKAAAAA?rs=1&pid=ImgDetMain",
          "product_num_offers": 20,
          "product_minimum_offer_price": "$359.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07NXDPLJ9",
          "quantity": 1,
          "product_title": "Apple AirPods Pro",
          "product_price": "$249.00",
          "product_original_price": "$279.00",
          "currency": "USD",
          "product_star_rating": "4.8",
          "product_num_ratings": 28000,
          "product_url": "https://www.amazon.com/dp/B07NXDPLJ9",
          "product_photo": "https://m.media-amazon.com/images/I/71zny7BTRlL._AC_UY654_FMwebp_QL65_.jpg",
          "product_num_offers": 30,
          "product_minimum_offer_price": "$239.00",
          "is_best_seller": true,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "15K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B0863BQMF5",
          "quantity": 1,
          "product_title": "Sennheiser PXC 550-II",
          "product_price": "$229.95",
          "product_original_price": "$349.95",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 6200,
          "product_url": "https://www.amazon.com/dp/B0863BQMF5",
          "product_photo": "https://th.bing.com/th/id/OIP.zKbYvuPREuV9MEtbUisyKQHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 18,
          "product_minimum_offer_price": "$219.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B088HM9BZB",
          "quantity": 1,
          "product_title": "Jabra Elite 85h",
          "product_price": "$229.99",
          "product_original_price": "$249.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 5300,
          "product_url": "https://www.amazon.com/dp/B088HM9BZB",
          "product_photo": "https://th.bing.com/th/id/OIP.WABsew5Ey2wYudrWqrXtBAHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$219.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08J5FYSX4",
          "quantity": 1,
          "product_title": "SteelSeries Arctis 7P",
          "product_price": "$149.99",
          "product_original_price": "$179.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 4100,
          "product_url": "https://www.amazon.com/dp/B08J5FYSX4",
          "product_photo": "https://th.bing.com/th/id/OIP._NfFRlNw-9Dl2K2e3X0BeAHaFj?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$139.00",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "2K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07VDTH16V",
          "quantity": 1,
          "product_title": "Corsair HS60 Pro",
          "product_price": "$64.99",
          "product_original_price": "$69.99",
          "currency": "USD",
          "product_star_rating": "4.4",
          "product_num_ratings": 6900,
          "product_url": "https://www.amazon.com/dp/B07VDTH16V",
          "product_photo": "https://th.bing.com/th/id/OIP.2_U6sblKjM6N1RBCYyUo5AHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 12,
          "product_minimum_offer_price": "$59.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "5K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B07SMBLK7J",
          "quantity": 1,
          "product_title": "Razer Kraken",
          "product_price": "$69.99",
          "product_original_price": "$79.99",
          "currency": "USD",
          "product_star_rating": "4.6",
          "product_num_ratings": 8800,
          "product_url": "https://www.amazon.com/dp/B07SMBLK7J",
          "product_photo": "https://th.bing.com/th/id/OIP.RWykwHxOetVvilyYB63aZwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 15,
          "product_minimum_offer_price": "$64.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "6K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08L8K2TJ7",
          "quantity": 1,
          "product_title": "HyperX Cloud Stinger Core",
          "product_price": "$79.99",
          "product_original_price": "$89.99",
          "currency": "USD",
          "product_star_rating": "4.5",
          "product_num_ratings": 5300,
          "product_url": "https://www.amazon.com/dp/B08L8K2TJ7",
          "product_photo": "https://th.bing.com/th/id/OIP.KdI0h_KiBGJBhtYdYO77rAHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 10,
          "product_minimum_offer_price": "$74.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "4K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        },
        {
          "asin": "B08GLXTY2C",
          "quantity": 1,
          "product_title": "Logitech G Pro X",
          "product_price": "$129.99",
          "product_original_price": "$149.99",
          "currency": "USD",
          "product_star_rating": "4.7",
          "product_num_ratings": 3900,
          "product_url": "https://www.amazon.com/dp/B08GLXTY2C",
          "product_photo": "https://th.bing.com/th/id/OIP.hKYkZyE8roE5FlAMy83KAwHaHa?rs=1&pid=ImgDetMain",
          "product_num_offers": 8,
          "product_minimum_offer_price": "$119.99",
          "is_best_seller": false,
          "is_amazon_choice": true,
          "is_prime": true,
          "climate_pledge_friendly": false,
          "sales_volume": "3K+ bought in past month",
          "delivery": "FREE delivery Sun, Jul 7 Or fastest delivery Tomorrow, Jul 3"
        }
        // Add other headsets products here
      ]
    }
  }
};

export default data;
